<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>xml</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^\s*(&lt;[^!?%/](?!.+?(/&gt;|&lt;/.+?&gt;))|&lt;[!%]--(?!.+?--%?&gt;)|&lt;%[!]?(?!.+?%&gt;))</string>
	<key>foldingStopMarker</key>
	<string>^\s*(&lt;/[^&gt;]+&gt;|[/%]&gt;|--&gt;)\s*$</string>
	<key>name</key>
	<string>Docbook 5</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.xml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.localname.xml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.localname.xml</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.xml</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.xml</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.section.docbook5</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.xml</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.xml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(&lt;)(sect\d) (xml:id)=((")sec.(.*)("))(&gt;)</string>
			<key>name</key>
			<string>meta.tag.xml</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.xml</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.xml.docbook5</string>
	<key>uuid</key>
	<string>9358FEF5-CDA6-4693-A776-C49FB7E83B36</string>
</dict>
</plist>
